SECTIONS_10K = (
    "BUSINESS",  # ITEM 1
    "RISK_FACTORS",  # ITEM 1A
    "UNRESOLVED_STAFF_COMMENTS",  # ITEM 1B
    "PROPERTIES",  # ITEM 2
    "LEGAL_PROCEEDINGS",  # ITEM 3
    "MINE_SAFETY",  # ITEM 4
    "MARKET_FOR_REGISTRANT_COMMON_EQUITY",  # ITEM 5
    # NOTE(robinson) - ITEM 6 is "RESERVED"
    "MANAGEMENT_DISCUSSION",  # ITEM 7
    "MARKET_RISK_DISCLOSURES",  # ITEM 7A
    "FINANCIAL_STATEMENTS",  # ITEM 8
    "ACCOUNTING_DISAGREEMENTS",  # ITEM 9
    "CONTROLS_AND_PROCEDURES",  # ITEM 9A
    # NOTE(robinson) - ITEM 9B is other information
    "FOREIGN_JURISDICTIONS",  # ITEM 9C
    "MANAGEMENT",  # ITEM 10
    "COMPENSATION",  # ITEM 11
    "PRINCIPAL_STOCKHOLDERS",  # ITEM 12
    "RELATED_PARTY_TRANSACTIONS",  # ITEM 13
    "ACCOUNTING_FEES",  # ITEM 14
    "EXHIBITS",  # ITEM 15
    "FORM_SUMMARY",  # ITEM 16
)

# NOTE(robinson) - Sections are listed in the following document from SEC
# ref: https://www.sec.gov/files/form10-q.pdf
SECTIONS_10Q = (
    # Part I - Financial information
    "FINANCIAL_STATEMENTS",  # ITEM 1
    "MANAGEMENT_DISCUSSION",  # ITEM 2
    "MARKET_RISK_DISCLOSURES",  # ITEM 3
    "CONTROLS_AND_PROCEDURES",  # ITEM 4
    # Part II - Other information
    "LEGAL_PROCEEDINGS",  # ITEM 1
    "RISK_FACTORS",  # ITEM 1A
    "USE_OF_PROCEEDS",  # ITEM 2
    "DEFAULTS",  # ITEM 3
    "MINE_SAFETY",  # ITEM 4
    "OTHER_INFORMATION",  # ITEM 5
)

SECTIONS_S1 = [
    "PROSPECTUS_SUMMARY",
    "ABOUT_PROSPECTUS",
    "FORWARD_LOOKING_STATEMENTS",
    "RISK_FACTORS",
    "USE_OF_PROCEEDS",
    "DIVIDEND_POLICY",
    "CAPITALIZATION",
    "DILUTION",
    "MANAGEMENT_DISCUSSION",
    "BUSINESS",
    "MANAGEMENT",
    "COMPENSATION",
    "RELATED_PARTY_TRANSACTIONS",
    "PRINCIPAL_STOCKHOLDERS",
    "DESCRIPTION_OF_STOCK",
    "DESCRIPTION_OF_DEBT",
    "FUTURE_SALE",
    "US_TAX",
    "UNDERWRITING",
    "LEGAL_MATTERS",
    "EXPERTS",
    "MORE_INFORMATION",
]
