# generated by datamodel-codegen:
#   filename:  spec.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field, constr


class PokeApiConfig(BaseModel):
    class Config:
        extra = Extra.allow

    pokemon_name: constr(regex=r'^[a-z0-9_\-]+$') = Field(
        ...,
        description='Pokemon requested from the API.',
        examples=['ditto', 'luxray', 'snorlax'],
        title='Pokemon Name',
    )
